### ISSUE TITLE
mina puma:stop => puma is not running.

### ISSUE THREAD

**Issue by lubekpl** [sandelius/mina-puma#11]
Hi!

I have a little bit of a problem - using mina-puma I can start my app but can not stop it. When I try mina puma:stop I get an error saying that puma is not running. Am I missing some configuration?

I'm using rvm, and both times it selects the correct ruby and gemset version.

my puma.rb conf file
```ruby
bind 'unix:///home/user_name/apps/app_name/shared/tmp/sockets/puma.sock'
threads 2,8
workers 2

**Comment by lubekpl** [comment]
So, apparently the puma config file also needs 2 more lines to properly stop the puma instance

```ruby
state_path '/home/user_name/apps/app_name/shared/tmp/sockets/puma.state'
activate_control_app 'unix:///home/user_name/apps/app_name/shared/tmp/sockets/pumactl.sock

**Comment by sandelius** [comment]
@lubekpl yeah if you're using cluster mode than it's needed.
