### ISSUE TITLE
Looking for new maintainer

### ISSUE THREAD

**Issue by sandelius** [sandelius/mina-puma#19]
Since I'm not using Mina or Puma anymore I'm looking for a maintainer to take over the project.

**Comment by d4rky-pl** [comment]
@sandelius We're using both mina and puma extensively in Untitled Kingdom. I can take over maintaining this project :)

**Comment by sandelius** [comment]
Hey, fork the project and give me the new rubygems maintainer name and I'll transfer it xD

**Comment by d4rky-pl** [comment]
Here's the fork: https://github.com/untitledkingdom/mina-puma
Here's the rubygems maintainer name: *d4rky-pl*

**Comment by sandelius** [comment]
Now the ownership has been changed. Good luck :)

**Comment by d4rky-pl** [comment]
Thanks :) It might be a good idea to disable issues and pull requests on this repository to avoid confusion.

**Comment by sandelius** [comment]
good call
